# Generated by Django 3.2.7 on 2021-10-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211027_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
