# Generated by Django 3.2.7 on 2021-10-28 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='post',
            new_name='problem',
        ),
    ]
